version: "3.9"
services: 
  vue_application:
    container_name: vue_application
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 8080:8080
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules